/**
 * skill.md — Echo's portable skill-file format.
 *
 * A skill.md is the "executable specification" of a workflow: a
 * single markdown file that captures (a) the goal the user asked
 * for, (b) the plan the Skill Manager composed, (c) every browser
 * action the agent actually performed (with the real screenshots
 * from the headless browser inlined as data URIs), and (d) the run
 * metadata so the file is self-describing.
 *
 * Drop the file into any Echo workspace and dispatch it: the agent
 * can re-run the same workflow just by reading the file. The
 * `triggers`, `inputs`, and `outputs` frontmatter keys let Echo's
 * scheduling engine wire the skill into a Trigger / Schedule without
 * additional config.
 *
 * The format is deliberately readable as plain markdown — anyone
 * can open skill.md in any text editor and follow the workflow
 * without Echo installed.
 */

import type { AgentRecord, RunRecord } from "./stores";

/** Browser action record (mirrors the BrowserAction type in stores). */
interface BrowserAction {
  ts: string;
  kind: "navigate" | "click" | "type" | "extract" | "save" | "think";
  url?: string;
  label: string;
  detail?: string;
  screenshot?: string;
  elapsedMs?: number;
  real?: boolean;
}

interface SubTask {
  num: number;
  title: string;
  matchedSkill: string;
  parallel: boolean;
  estTime: string;
}

interface SkillInput {
  num: number;
  sample: Record<string, unknown>;
}

/**
 * Generate the skill.md file body for a given run + agent.
 * Pure function — no I/O, no DOM. Use `downloadSkillMd(run, agent)`
 * to actually trigger a browser download.
 */
export function generateSkillMd(
  run: RunRecord,
  agent: AgentRecord | null,
  options: { author?: string } = {}
): string {
  const actions = (run.actions ?? []) as BrowserAction[];
  const realActions = actions.filter((a) => a.real);
  const simActions = actions.filter((a) => !a.real);
  const navigateActions = actions.filter((a) => a.kind === "navigate");
  const extractActions = actions.filter((a) => a.kind === "extract");
  const screenshotActions = actions.filter(
    (a) => a.kind === "extract" && a.screenshot
  );

  // Distinct hostnames the agent visited (for the "sites" section)
  const hosts = Array.from(
    new Set(
      navigateActions
        .map((a) => a.url)
        .filter((u): u is string => !!u)
        .map((u) => {
          try {
            return new URL(u).host.replace(/^www\./, "");
          } catch {
            return u;
          }
        })
    )
  );

  // Sub-tasks from the plan (preferred) or from the agent record
  const subTasks: SubTask[] =
    (run as { skill?: { steps?: SubTask[] } }).skill?.steps?.map(
      (s: { num: number; title: string; detail?: string; at?: string }, i: number) => ({
        num: s.num,
        title: s.title,
        matchedSkill: s.detail ?? s.title,
        parallel: false,
        estTime: "—",
      })
    ) ??
    (agent?.subtasks ?? []).map((s) => ({
      num: s.num,
      title: s.title,
      matchedSkill: s.matchedSkill,
      parallel: s.parallel,
      estTime: s.estTime,
    }));

  const inputsDone = run.inputs.filter(
    (i) => (i.payload as { _status?: string } | null)?._status === "done"
  ).length;

  const totalElapsedSec = run.durationSec ?? elapsedFromTimestamps(run);

  const created = new Date().toISOString();
  const author = options.author ?? "Echo Skill Composer";

  // YAML frontmatter
  const fm: Record<string, unknown> = {
    name: agent?.name ?? "Untitled skill",
    description: agent?.goal ?? run.goal ?? "",
    created,
    source_run: run.id,
    source_agent: agent?.id ?? null,
    status: run.status,
    author,
    total_inputs: run.totalInputs,
    inputs_completed: inputsDone,
    total_actions: actions.length,
    real_browser_actions: realActions.length,
    simulated_actions: simActions.length,
    total_elapsed_seconds: totalElapsedSec,
    goal: run.goal ?? agent?.goal ?? "",
  };
  if (subTasks.length > 0) {
    fm.triggers = subTasks.map((s) => s.matchedSkill);
  }
  if (run.inputs.length > 0) {
    fm.sample_inputs = run.inputs.slice(0, 3).map((i) => i.payload);
  }

  // Build the body
  const lines: string[] = [];
  lines.push("---");
  for (const [k, v] of Object.entries(fm)) {
    lines.push(`${k}: ${yamlValue(v)}`);
  }
  lines.push("---");
  lines.push("");

  lines.push(`# ${agent?.name ?? "Echo skill"}`);
  lines.push("");
  lines.push(
    `> Auto-generated by Echo from run \`${run.id}\`${
      agent ? ` and agent \`${agent.id}\`` : ""
    }. Drop this file into any Echo workspace and re-dispatch.`
  );
  lines.push("");

  // Goal
  if (run.goal || agent?.goal) {
    lines.push("## Goal");
    lines.push("");
    lines.push(`> ${(run.goal ?? agent?.goal ?? "").trim()}`);
    lines.push("");
  }

  // When to use — derived from sub-tasks
  if (subTasks.length > 0) {
    lines.push("## When to use");
    lines.push("");
    for (const s of subTasks) {
      lines.push(`- ${s.title}`);
    }
    lines.push("");
  }

  // How it works — the composed plan
  if (subTasks.length > 0) {
    lines.push("## How it works");
    lines.push("");
    lines.push(
      "Echo's Skill Manager decomposed the goal into the following " +
        `sub-task${subTasks.length === 1 ? "" : "s"}, matched to learned ` +
        "skills from the library:"
    );
    lines.push("");
    for (const s of subTasks) {
      const parallel = s.parallel ? " · ⚡ parallel" : "";
      const skill = s.matchedSkill?.startsWith("NEW:") ? s.matchedSkill : s.matchedSkill;
      lines.push(`${s.num}. **${s.title}** — uses _${skill}_${parallel}`);
    }
    lines.push("");
  }

  // Step-by-step browser actions — the actual run trace
  if (actions.length > 0) {
    lines.push("## Step-by-step browser actions");
    lines.push("");
    lines.push(
      `The autonomous agent performed **${actions.length}** browser ` +
        `action${actions.length === 1 ? "" : "s"} while executing this run ` +
        `(${realActions.length} from a real headless Chromium, ` +
        `${simActions.length} simulated as fallback when the real browser ` +
        "was warming up or the target page was auth-walled):"
    );
    lines.push("");
    lines.push("| # | Kind | Site | Action | Real? |");
    lines.push("|---|------|------|--------|-------|");
    actions.forEach((a, i) => {
      const kindEmoji: Record<BrowserAction["kind"], string> = {
        navigate: "↗",
        click: "●",
        type: "✎",
        extract: "↓",
        save: "✓",
        think: "✦",
      };
      const site = a.url
        ? (() => {
            try {
              return new URL(a.url).host.replace(/^www\./, "");
            } catch {
              return a.url;
            }
          })()
        : "—";
      const real = a.real ? "✓" : "";
      const label = (a.label || "").replace(/\|/g, "\\|");
      const detail = a.detail ? ` — _${a.detail.replace(/\|/g, "\\|")}_` : "";
      lines.push(
        `| ${i + 1} | ${kindEmoji[a.kind]} ${a.kind} | ${site} | ${label}${detail} | ${real} |`
      );
    });
    lines.push("");
  }

  // Real browser screenshots
  if (screenshotActions.length > 0) {
    lines.push("## Real browser screenshots");
    lines.push("");
    lines.push(
      `The agent captured **${screenshotActions.length}** real screenshot${
        screenshotActions.length === 1 ? "" : "s"
      } ` +
        `from a headless Chromium on Cloud Run. The data URIs are embedded ` +
        "inline so this file is self-contained:"
    );
    lines.push("");
    for (const a of screenshotActions) {
      if (!a.screenshot) continue;
      const site = a.url
        ? (() => {
            try {
              return new URL(a.url).host.replace(/^www\./, "");
            } catch {
              return a.url;
            }
          })()
        : "page";
      const at = a.ts ? new Date(a.ts).toISOString() : "";
      lines.push(`### ${site} — captured at ${at}`);
      lines.push("");
      lines.push(`![Screenshot of ${site} — ${a.label}](${a.screenshot})`);
      lines.push("");
      if (a.detail) lines.push(`_${a.detail}_`);
      lines.push("");
    }
  }

  // Inputs / outputs (for trigger wiring)
  if (run.inputs.length > 0) {
    lines.push("## Inputs");
    lines.push("");
    lines.push(
      `The agent processed **${run.totalInputs}** input${
        run.totalInputs === 1 ? "" : "s"
      } for this run. Sample input shapes:`
    );
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(run.inputs.slice(0, 3).map((i) => i.payload), null, 2));
    lines.push("```");
    lines.push("");
  }

  // Run metadata
  lines.push("## Run metadata");
  lines.push("");
  lines.push(`- **Run id:** \`${run.id}\``);
  if (agent?.id) lines.push(`- **Agent id:** \`${agent.id}\``);
  if (run.startedAt) lines.push(`- **Started:** ${run.startedAt}`);
  if (run.finishedAt) lines.push(`- **Finished:** ${run.finishedAt}`);
  if (totalElapsedSec)
    lines.push(`- **Total time:** ${formatDuration(totalElapsedSec)}`);
  if (hosts.length > 0) {
    lines.push(`- **Sites visited:** ${hosts.map((h) => `\`${h}\``).join(", ")}`);
  }
  if (run.gcp) lines.push(`- **GCP status:** ${run.gcp}`);
  if (run.message) lines.push(`- **Server message:** ${run.message}`);
  lines.push(`- **Real headless actions:** ${realActions.length}`);
  lines.push(`- **Simulated actions:** ${simActions.length}`);
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(
    `_This file was generated by [Echo](https://echo-one-liard.vercel.app) ` +
      `on ${created}. To re-run, upload it via the Skill Composer's "Load from file" ` +
      "action or drop it into the Echo skill library._"
  );
  lines.push("");

  return lines.join("\n");
}

function yamlValue(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "string") {
    // Quote if it contains a colon, hash, leading/trailing space, or starts with a special char
    if (/[:#\n]/.test(v) || /^\s|\s$/.test(v) || v === "") {
      return `"${v.replace(/"/g, '\\"')}"`;
    }
    return v;
  }
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return "[]";
    const items = v.map((x) => `  - ${yamlValue(x)}`);
    return `\n${items.join("\n")}`;
  }
  if (typeof v === "object") {
    const obj = v as Record<string, unknown>;
    const keys = Object.keys(obj);
    if (keys.length === 0) return "{}";
    return keys
      .map((k) => `  ${k}: ${yamlValue(obj[k])}`)
      .join("\n");
  }
  return String(v);
}

function elapsedFromTimestamps(run: RunRecord): number {
  if (!run.startedAt) return 0;
  const start = new Date(run.startedAt).getTime();
  const end = run.finishedAt ? new Date(run.finishedAt).getTime() : Date.now();
  return Math.max(0, Math.floor((end - start) / 1000));
}

function formatDuration(sec: number): string {
  if (sec < 60) return `${sec}s`;
  const m = Math.floor(sec / 60);
  const s = sec % 60;
  if (m < 60) return `${m}m ${String(s).padStart(2, "0")}s`;
  const h = Math.floor(m / 60);
  return `${h}h ${String(m % 60).padStart(2, "0")}m`;
}

/**
 * Trigger a browser download of the skill.md file. Pure browser
 * API — no server roundtrip. The file is named after the run so
 * multiple downloads don't collide.
 */
export function downloadSkillMd(
  run: RunRecord,
  agent: AgentRecord | null,
  options: { author?: string } = {}
): void {
  if (typeof window === "undefined") return;
  const content = generateSkillMd(run, agent, options);
  const safeName = (agent?.name ?? run.id)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "echo-skill";
  const filename = `${safeName}-${run.id.slice(-12)}.md`;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Defer revocation so the browser has time to start the download
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
